export const Cidades = [
  { id: 1, nome: "Andorinha", dias: 7, dificuldade: false, favorito: false },
  { id: 2, nome: "Angical", dias: 10, dificuldade: false, favorito: false },
  { id: 3, nome: "Antonio Gonçalves", dias: 7, dificuldade: false, favorito: false },
  { id: 4, nome: "Araçás", dias: 7, dificuldade: false, favorito: false },
  { id: 5, nome: "Araci", dias: 10, dificuldade: false, favorito: false },
  { id: 6, nome: "Aramari", dias: 7, dificuldade: false, favorito: false },
  { id: 7, nome: "Baianópolis", dias: 5, dificuldade: false, favorito: false },
  { id: 8, nome: "Banzaê", dias: 10, dificuldade: false, favorito: false },
  { id: 9, nome: "Barra", dias: 7, dificuldade: false, favorito: false },
  { id: 10, nome: "Barreiras", dias: 2, dificuldade: false, favorito: false },
  { id: 11, nome: "Barrocas", dias: 5, dificuldade: false, favorito: false },
  { id: 12, nome: "Biritinga", dias: 5, dificuldade: false, favorito: false },
  { id: 13, nome: "Bom Jesus da Lapa", dias: 7, dificuldade: false, favorito: false },
  { id: 14, nome: "Boquira", dias: 10, dificuldade: false, favorito: false },
  { id: 15, nome: "Botuporã", dias: 10, dificuldade: false, favorito: false },
  { id: 16, nome: "Brejolândia", dias: 10, dificuldade: false, favorito: false },
  { id: 17, nome: "Brumado", dias: 5, dificuldade: false, favorito: false },
  { id: 18, nome: "Buritirama", dias: 10, dificuldade: false, favorito: false },
  { id: 19, nome: "Caetité", dias: 10, dificuldade: false, favorito: false },
  { id: 20, nome: "Campo Formoso", dias: 7, dificuldade: false, favorito: false },
  { id: 21, nome: "Canápolis", dias: 10, dificuldade: false, favorito: false },
  { id: 22, nome: "Candeal", dias: 5, dificuldade: false, favorito: false },
  { id: 23, nome: "Candiba", dias: 10, dificuldade: false, favorito: false },
  { id: 24, nome: "Cansanção", dias: 7, dificuldade: false, favorito: false },
  { id: 25, nome: "Carinhanha", dias: 10, dificuldade: false, favorito: false },
  { id: 26, nome: "Catolândia", dias: 10, dificuldade: false, favorito: false },
  { id: 27, nome: "Central", dias: 7, dificuldade: false, favorito: false },
  { id: 28, nome: "Conceição do Coité", dias: 5, dificuldade: false, favorito: false },
  { id: 29, nome: "Cotegipe", dias: 10, dificuldade: false, favorito: false },
  { id: 30, nome: "Cristópolis", dias: 10, dificuldade: false, favorito: false },
  { id: 31, nome: "Dom Basílio", dias: 10, dificuldade: false, favorito: false },
  { id: 32, nome: "Entre Rios", dias: 7, dificuldade: false, favorito: false },
  { id: 33, nome: "Euclides da Cunha", dias: 5, dificuldade: false, favorito: false },
  { id: 34, nome: "Feira de Santana", dias: 2, dificuldade: false, favorito: false },
  { id: 35, nome: "Filadélfia", dias: 7, dificuldade: false, favorito: false },
  { id: 36, nome: "Formosa do Rio Preto", dias: 10, dificuldade: false, favorito: false },
  { id: 37, nome: "Guanambi", dias: 5, dificuldade: false, favorito: false },
  { id: 38, nome: "Iaçu", dias: 7, dificuldade: false, favorito: false },
  { id: 39, nome: "Ibiassucê", dias: 10, dificuldade: false, favorito: false },
  { id: 40, nome: "Ibitiara", dias: 7, dificuldade: false, favorito: false },
  { id: 41, nome: "Ibotirama", dias: 3, dificuldade: false, favorito: false },
  { id: 42, nome: "Ichu", dias: 5, dificuldade: false, favorito: false },
  { id: 43, nome: "Igaporã", dias: 10, dificuldade: false, favorito: false },
  { id: 44, nome: "Inhambupe", dias: 7, dificuldade: false, favorito: false },
  { id: 45, nome: "Iraquara", dias: 7, dificuldade: false, favorito: false },
  { id: 46, nome: "Irecê", dias: 7, dificuldade: false, favorito: false },
  { id: 47, nome: "Itaberaba", dias: 2, dificuldade: false, favorito: false },
  { id: 48, nome: "Itanagra", dias: 7, dificuldade: false, favorito: false },
  { id: 49, nome: "Iuiu", dias: 10, dificuldade: false, favorito: false },
  { id: 50, nome: "Jaguarari", dias: 7, dificuldade: false, favorito: false },

  { id: 51, nome: "Jussara", dias: 7, dificuldade: false, favorito: false },
  { id: 52, nome: "Lagoa Real", dias: 10, dificuldade: false, favorito: false },
  { id: 53, nome: "Lamarão", dias: 5, dificuldade: false, favorito: false },
  { id: 54, nome: "Lençóis", dias: 7, dificuldade: false, favorito: false },
  { id: 55, nome: "Livramento de Nossa Senhora", dias: 10, dificuldade: false, favorito: false },
  { id: 56, nome: "Luis Eduardo Magalhães", dias: 3, dificuldade: false, favorito: false },
  { id: 57, nome: "Macajuba", dias: 7, dificuldade: false, favorito: false },
  { id: 58, nome: "Macaúbas", dias: 10, dificuldade: false, favorito: false },
  { id: 59, nome: "Maetinga", dias: 10, dificuldade: false, favorito: false },
  { id: 60, nome: "Malhada de Pedras", dias: 10, dificuldade: false, favorito: false },
  { id: 61, nome: "Mansidão", dias: 10, dificuldade: false, favorito: false },
  { id: 62, nome: "Matina", dias: 10, dificuldade: false, favorito: false },
  { id: 63, nome: "Monte Santo", dias: 7, dificuldade: false, favorito: false },
  { id: 64, nome: "Muquém do São Francisco", dias: 10, dificuldade: false, favorito: false },
  { id: 65, nome: "Oliveira dos Brejinhos", dias: 10, dificuldade: false, favorito: false },
  { id: 66, nome: "Ouriçangas", dias: 7, dificuldade: false, favorito: false },
  { id: 67, nome: "Palmas de Monte Alto", dias: 10, dificuldade: false, favorito: false },
  { id: 68, nome: "Palmeiras", dias: 7, dificuldade: false, favorito: false },
  { id: 69, nome: "Paramirim", dias: 10, dificuldade: false, favorito: false },
  { id: 70, nome: "Paratinga", dias: 5, dificuldade: false, favorito: false },
  { id: 71, nome: "Pedrão", dias: 7, dificuldade: false, favorito: false },
  { id: 72, nome: "Pindaí", dias: 10, dificuldade: false, favorito: false },
  { id: 73, nome: "Pindobaçu", dias: 7, dificuldade: false, favorito: false },
  { id: 74, nome: "Ponto Novo", dias: 7, dificuldade: false, favorito: false },
  { id: 75, nome: "Presidente Dutra", dias: 7, dificuldade: false, favorito: false },
  { id: 76, nome: "Quijingue", dias: 7, dificuldade: false, favorito: false },
  { id: 77, nome: "Riachão das Neves", dias: 10, dificuldade: false, favorito: false },
  { id: 78, nome: "Ribeira do Pombal", dias: 7, dificuldade: false, favorito: false },
  { id: 79, nome: "Rio do Antônio", dias: 10, dificuldade: false, favorito: false },
  { id: 80, nome: "Rio do Pires", dias: 10, dificuldade: false, favorito: false },
  { id: 81, nome: "Ruy Barbosa", dias: 7, dificuldade: false, favorito: false },
  { id: 82, nome: "Santa Maria da Vitória", dias: 7, dificuldade: false, favorito: false },
  { id: 83, nome: "Santa Rita de Cássia", dias: 10, dificuldade: false, favorito: false },
  { id: 84, nome: "Santana", dias: 10, dificuldade: false, favorito: false },
  { id: 85, nome: "São Desidério", dias: 5, dificuldade: false, favorito: false },
  { id: 86, nome: "São Gabriel", dias: 7, dificuldade: false, favorito: false },
  { id: 87, nome: "São Félix do Coribe", dias: 7, dificuldade: false, favorito: false },
  { id: 88, nome: "Seabra", dias: 2, dificuldade: false, favorito: false },
  { id: 89, nome: "Senhor do Bonfim", dias: 5, dificuldade: false, favorito: false },
  { id: 90, nome: "Serra do Ramalho", dias: 7, dificuldade: false, favorito: false },
  { id: 91, nome: "Serra Dourada", dias: 10, dificuldade: false, favorito: false },
  { id: 92, nome: "Serrinha", dias: 5, dificuldade: false, favorito: false },
  { id: 93, nome: "Sítio do Mato", dias: 7, dificuldade: false, favorito: false },
  { id: 94, nome: "Tabocas do Brejo Velho", dias: 10, dificuldade: false, favorito: false },
  { id: 95, nome: "Tanque Novo", dias: 10, dificuldade: false, favorito: false },
  { id: 96, nome: "Teofilândia", dias: 5, dificuldade: false, favorito: false },
  { id: 97, nome: "Tucano", dias: 7, dificuldade: false, favorito: false },
  { id: 98, nome: "Uibaí", dias: 7, dificuldade: false, favorito: false },
  { id: 99, nome: "Urandi", dias: 7, dificuldade: false, favorito: false },
  { id: 100, nome: "Wanderley", dias: 10, dificuldade: false, favorito: false }
]